-- ============================================================
-- Seed: produtos do catálogo de pedidos + tamanhos/SKUs
-- Dados configurados manualmente em dev, migrados para produção.
-- Usa ON CONFLICT para ser idempotente (pode rodar mais de uma vez).
-- ============================================================

-- Produtos (apenas os ativos)
INSERT INTO order_catalog_products (id, name, photo_url, price_pc, price_mn, reference_codigo, active) VALUES (3, 'Blusa Alcinha', '/uploads/order-products/product-3-1774227076835.webp', 8.50, 8.50, '00353', true) ON CONFLICT DO NOTHING;
INSERT INTO order_catalog_products (id, name, photo_url, price_pc, price_mn, reference_codigo, active) VALUES (4, 'Bermudinha Ciclista', '/uploads/order-products/product-4-1774227679313.jpg', 6.50, 6.38, '00388', true) ON CONFLICT DO NOTHING;
INSERT INTO order_catalog_products (id, name, photo_url, price_pc, price_mn, reference_codigo, active) VALUES (5, 'Regata Feminina', '/uploads/order-products/product-5-1774227806621.png', 8.50, 8.50, '00354', true) ON CONFLICT DO NOTHING;
INSERT INTO order_catalog_products (id, name, photo_url, price_pc, price_mn, reference_codigo, active) VALUES (6, 'Camiseta com Aplique Manga Curta - Menino', '/uploads/order-products/product-6-1774227900701.png', 8.50, 8.50, '00399', true) ON CONFLICT DO NOTHING;
INSERT INTO order_catalog_products (id, name, photo_url, price_pc, price_mn, reference_codigo, active) VALUES (7, 'Camiseta com Aplique Manga Longa Menino', '/uploads/order-products/product-7-1774228076713.png', 11.50, 11.50, '00511', true) ON CONFLICT DO NOTHING;
INSERT INTO order_catalog_products (id, name, photo_url, price_pc, price_mn, reference_codigo, active) VALUES (8, 'Camiseta com Aplique Manga Curta - Menina', '/uploads/order-products/product-8-1774228186133.png', 8.50, 8.50, '00591', true) ON CONFLICT DO NOTHING;
INSERT INTO order_catalog_products (id, name, photo_url, price_pc, price_mn, reference_codigo, active) VALUES (9, 'Legging Infantil', '/uploads/order-products/product-9-1774228361139.png', 11.50, 11.50, '00404', true) ON CONFLICT DO NOTHING;
INSERT INTO order_catalog_products (id, name, photo_url, price_pc, price_mn, reference_codigo, active) VALUES (12, 'Calça Moleton', '/uploads/order-products/product-12-1774228525786.jpg', 10.00, 10.00, '00467', true) ON CONFLICT DO NOTHING;
INSERT INTO order_catalog_products (id, name, photo_url, price_pc, price_mn, reference_codigo, active) VALUES (13, 'Blusa Cacharrel', '/uploads/order-products/product-13-1774228605502.jpg', 11.50, 11.50, '00250', true) ON CONFLICT DO NOTHING;
INSERT INTO order_catalog_products (id, name, photo_url, price_pc, price_mn, reference_codigo, active) VALUES (14, 'Camiseta Manga longa com Gola Careca', '/uploads/order-products/product-14-1774228732284.jpg', 10.90, 10.90, '00416', true) ON CONFLICT DO NOTHING;
INSERT INTO order_catalog_products (id, name, photo_url, price_pc, price_mn, reference_codigo, active) VALUES (15, 'Bermuda Moletinho - Menino', '/uploads/order-products/product-15-1774228857009.jpeg', 8.50, 8.50, '00400', true) ON CONFLICT DO NOTHING;
INSERT INTO order_catalog_products (id, name, photo_url, price_pc, price_mn, reference_codigo, active) VALUES (16, 'Body Canelado', '/uploads/order-products/product-16-1774228936614.webp', 12.00, 12.00, '00565', true) ON CONFLICT DO NOTHING;
INSERT INTO order_catalog_products (id, name, photo_url, price_pc, price_mn, reference_codigo, active) VALUES (17, 'Conjunto Soft', '/uploads/order-products/product-17-1774229148020.webp', 19.00, 19.00, '701', true) ON CONFLICT DO NOTHING;
INSERT INTO order_catalog_products (id, name, photo_url, price_pc, price_mn, reference_codigo, active) VALUES (18, 'Pijama Curto - Feminino', '/uploads/order-products/product-18-1774229333277.jpg', 14.90, 14.90, '509', true) ON CONFLICT DO NOTHING;
INSERT INTO order_catalog_products (id, name, photo_url, price_pc, price_mn, reference_codigo, active) VALUES (19, 'Pijama Longo - Feminino', '/uploads/order-products/product-19-1774229496115.jpeg', 15.70, 15.70, '00274', true) ON CONFLICT DO NOTHING;
INSERT INTO order_catalog_products (id, name, photo_url, price_pc, price_mn, reference_codigo, active) VALUES (20, 'Pijama Curto - Masculino', '/uploads/order-products/product-20-1774229715177.jpeg', 14.90, 14.90, '00612', true) ON CONFLICT DO NOTHING;
INSERT INTO order_catalog_products (id, name, photo_url, price_pc, price_mn, reference_codigo, active) VALUES (21, 'Pijama Longo - Menino', '/uploads/order-products/product-21-1774229780090.jpeg', 15.70, 15.70, '317', true) ON CONFLICT DO NOTHING;
INSERT INTO order_catalog_products (id, name, photo_url, price_pc, price_mn, reference_codigo, active) VALUES (22, 'Trijunto verão - Menino', '/uploads/order-products/product-22-1774229884628.jpeg', 20.50, 19.50, '00161', true) ON CONFLICT DO NOTHING;
INSERT INTO order_catalog_products (id, name, photo_url, price_pc, price_mn, reference_codigo, active) VALUES (23, 'Trijunto verão - Menina', '/uploads/order-products/product-23-1774229956848.jpg', 20.50, 19.50, '00127', true) ON CONFLICT DO NOTHING;
INSERT INTO order_catalog_products (id, name, photo_url, price_pc, price_mn, reference_codigo, active) VALUES (24, 'Trijunto Inverno - Menina', '/uploads/order-products/product-24-1774230070237.jpeg', 19.50, 19.50, '00133', true) ON CONFLICT DO NOTHING;

-- Ajusta sequence para próximo ID
SELECT setval('order_catalog_products_id_seq', (SELECT COALESCE(MAX(id), 1) FROM order_catalog_products));

-- Tamanhos / SKUs
INSERT INTO order_catalog_sizes (product_id, size_name, sisplan_sku, sort_order) VALUES (3, '1', '00353-00061-1', 0) ON CONFLICT (product_id, size_name) DO NOTHING;
INSERT INTO order_catalog_sizes (product_id, size_name, sisplan_sku, sort_order) VALUES (3, '2', '00353-00001-2', 1) ON CONFLICT (product_id, size_name) DO NOTHING;
INSERT INTO order_catalog_sizes (product_id, size_name, sisplan_sku, sort_order) VALUES (3, '3', '00353-00062-3', 2) ON CONFLICT (product_id, size_name) DO NOTHING;
INSERT INTO order_catalog_sizes (product_id, size_name, sisplan_sku, sort_order) VALUES (3, '4', '00353-00063-4', 3) ON CONFLICT (product_id, size_name) DO NOTHING;
INSERT INTO order_catalog_sizes (product_id, size_name, sisplan_sku, sort_order) VALUES (3, '6', '00353-9-6', 4) ON CONFLICT (product_id, size_name) DO NOTHING;
INSERT INTO order_catalog_sizes (product_id, size_name, sisplan_sku, sort_order) VALUES (3, '8', '00353-00085-8', 5) ON CONFLICT (product_id, size_name) DO NOTHING;
INSERT INTO order_catalog_sizes (product_id, size_name, sisplan_sku, sort_order) VALUES (3, '10', '00353-00043-10', 6) ON CONFLICT (product_id, size_name) DO NOTHING;
INSERT INTO order_catalog_sizes (product_id, size_name, sisplan_sku, sort_order) VALUES (4, '1', '00388-00079-1', 0) ON CONFLICT (product_id, size_name) DO NOTHING;
INSERT INTO order_catalog_sizes (product_id, size_name, sisplan_sku, sort_order) VALUES (4, '2', '00388-00082-2', 1) ON CONFLICT (product_id, size_name) DO NOTHING;
INSERT INTO order_catalog_sizes (product_id, size_name, sisplan_sku, sort_order) VALUES (4, '3', '00388-00113-3', 2) ON CONFLICT (product_id, size_name) DO NOTHING;
INSERT INTO order_catalog_sizes (product_id, size_name, sisplan_sku, sort_order) VALUES (4, '4', '00388-00082-4', 3) ON CONFLICT (product_id, size_name) DO NOTHING;
INSERT INTO order_catalog_sizes (product_id, size_name, sisplan_sku, sort_order) VALUES (4, '6', '00388-00113-6', 4) ON CONFLICT (product_id, size_name) DO NOTHING;
INSERT INTO order_catalog_sizes (product_id, size_name, sisplan_sku, sort_order) VALUES (4, '8', '00388-00051-8', 5) ON CONFLICT (product_id, size_name) DO NOTHING;
INSERT INTO order_catalog_sizes (product_id, size_name, sisplan_sku, sort_order) VALUES (4, '10', '00388-00089-10', 6) ON CONFLICT (product_id, size_name) DO NOTHING;
INSERT INTO order_catalog_sizes (product_id, size_name, sisplan_sku, sort_order) VALUES (5, '1', '00354-00057-1', 0) ON CONFLICT (product_id, size_name) DO NOTHING;
INSERT INTO order_catalog_sizes (product_id, size_name, sisplan_sku, sort_order) VALUES (5, '2', '00354-00039-2', 1) ON CONFLICT (product_id, size_name) DO NOTHING;
INSERT INTO order_catalog_sizes (product_id, size_name, sisplan_sku, sort_order) VALUES (5, '3', '00354-00003-3', 2) ON CONFLICT (product_id, size_name) DO NOTHING;
INSERT INTO order_catalog_sizes (product_id, size_name, sisplan_sku, sort_order) VALUES (5, '4', '00354-00067-4', 3) ON CONFLICT (product_id, size_name) DO NOTHING;
INSERT INTO order_catalog_sizes (product_id, size_name, sisplan_sku, sort_order) VALUES (5, '6', '00354-00079-6', 4) ON CONFLICT (product_id, size_name) DO NOTHING;
INSERT INTO order_catalog_sizes (product_id, size_name, sisplan_sku, sort_order) VALUES (5, '8', '00354-00001-8', 5) ON CONFLICT (product_id, size_name) DO NOTHING;
INSERT INTO order_catalog_sizes (product_id, size_name, sisplan_sku, sort_order) VALUES (5, '10', '00354-00082-10', 6) ON CONFLICT (product_id, size_name) DO NOTHING;
INSERT INTO order_catalog_sizes (product_id, size_name, sisplan_sku, sort_order) VALUES (6, '1', '00399-00061-1', 0) ON CONFLICT (product_id, size_name) DO NOTHING;
INSERT INTO order_catalog_sizes (product_id, size_name, sisplan_sku, sort_order) VALUES (6, '2', '00399-00092-2', 1) ON CONFLICT (product_id, size_name) DO NOTHING;
INSERT INTO order_catalog_sizes (product_id, size_name, sisplan_sku, sort_order) VALUES (6, '3', '00399-00039-3', 2) ON CONFLICT (product_id, size_name) DO NOTHING;
INSERT INTO order_catalog_sizes (product_id, size_name, sisplan_sku, sort_order) VALUES (6, '4', '00399-00082-4', 3) ON CONFLICT (product_id, size_name) DO NOTHING;
INSERT INTO order_catalog_sizes (product_id, size_name, sisplan_sku, sort_order) VALUES (6, '6', '00399-00058-6', 4) ON CONFLICT (product_id, size_name) DO NOTHING;
INSERT INTO order_catalog_sizes (product_id, size_name, sisplan_sku, sort_order) VALUES (6, '8', '00399-00098-8', 5) ON CONFLICT (product_id, size_name) DO NOTHING;
INSERT INTO order_catalog_sizes (product_id, size_name, sisplan_sku, sort_order) VALUES (6, '10', '00399-00083-10', 6) ON CONFLICT (product_id, size_name) DO NOTHING;
INSERT INTO order_catalog_sizes (product_id, size_name, sisplan_sku, sort_order) VALUES (7, '1', '00511-00090-1', 0) ON CONFLICT (product_id, size_name) DO NOTHING;
INSERT INTO order_catalog_sizes (product_id, size_name, sisplan_sku, sort_order) VALUES (7, '2', '00511-00103-2', 1) ON CONFLICT (product_id, size_name) DO NOTHING;
INSERT INTO order_catalog_sizes (product_id, size_name, sisplan_sku, sort_order) VALUES (7, '3', '00511-00077-3', 2) ON CONFLICT (product_id, size_name) DO NOTHING;
INSERT INTO order_catalog_sizes (product_id, size_name, sisplan_sku, sort_order) VALUES (7, '4', '00511-00133-4', 3) ON CONFLICT (product_id, size_name) DO NOTHING;
INSERT INTO order_catalog_sizes (product_id, size_name, sisplan_sku, sort_order) VALUES (7, '6', '00511-00117-6', 4) ON CONFLICT (product_id, size_name) DO NOTHING;
INSERT INTO order_catalog_sizes (product_id, size_name, sisplan_sku, sort_order) VALUES (7, '8', '00511-00117-8', 5) ON CONFLICT (product_id, size_name) DO NOTHING;
INSERT INTO order_catalog_sizes (product_id, size_name, sisplan_sku, sort_order) VALUES (7, '10', '00511-00082-10', 6) ON CONFLICT (product_id, size_name) DO NOTHING;
INSERT INTO order_catalog_sizes (product_id, size_name, sisplan_sku, sort_order) VALUES (8, '1', '00591-00039-1', 0) ON CONFLICT (product_id, size_name) DO NOTHING;
INSERT INTO order_catalog_sizes (product_id, size_name, sisplan_sku, sort_order) VALUES (8, '2', '00591-00083-2', 1) ON CONFLICT (product_id, size_name) DO NOTHING;
INSERT INTO order_catalog_sizes (product_id, size_name, sisplan_sku, sort_order) VALUES (8, '3', '00591-00082-3', 2) ON CONFLICT (product_id, size_name) DO NOTHING;
INSERT INTO order_catalog_sizes (product_id, size_name, sisplan_sku, sort_order) VALUES (8, '4', '00591-00096-4', 3) ON CONFLICT (product_id, size_name) DO NOTHING;
INSERT INTO order_catalog_sizes (product_id, size_name, sisplan_sku, sort_order) VALUES (8, '6', '00591-00115-6', 4) ON CONFLICT (product_id, size_name) DO NOTHING;
INSERT INTO order_catalog_sizes (product_id, size_name, sisplan_sku, sort_order) VALUES (8, '8', '00591-00103-8', 5) ON CONFLICT (product_id, size_name) DO NOTHING;
INSERT INTO order_catalog_sizes (product_id, size_name, sisplan_sku, sort_order) VALUES (8, '10', '00591-00077-10', 6) ON CONFLICT (product_id, size_name) DO NOTHING;
INSERT INTO order_catalog_sizes (product_id, size_name, sisplan_sku, sort_order) VALUES (9, '1', '00404-00107-1', 0) ON CONFLICT (product_id, size_name) DO NOTHING;
INSERT INTO order_catalog_sizes (product_id, size_name, sisplan_sku, sort_order) VALUES (9, '2', '00404-00145-2', 1) ON CONFLICT (product_id, size_name) DO NOTHING;
INSERT INTO order_catalog_sizes (product_id, size_name, sisplan_sku, sort_order) VALUES (9, '3', '00404-00007-3', 2) ON CONFLICT (product_id, size_name) DO NOTHING;
INSERT INTO order_catalog_sizes (product_id, size_name, sisplan_sku, sort_order) VALUES (9, '4', '00404-00080-4', 3) ON CONFLICT (product_id, size_name) DO NOTHING;
INSERT INTO order_catalog_sizes (product_id, size_name, sisplan_sku, sort_order) VALUES (9, '6', '00404-00103-6', 4) ON CONFLICT (product_id, size_name) DO NOTHING;
INSERT INTO order_catalog_sizes (product_id, size_name, sisplan_sku, sort_order) VALUES (9, '8', '00404-9-8', 5) ON CONFLICT (product_id, size_name) DO NOTHING;
INSERT INTO order_catalog_sizes (product_id, size_name, sisplan_sku, sort_order) VALUES (9, '10', '00404-00082-10', 6) ON CONFLICT (product_id, size_name) DO NOTHING;
INSERT INTO order_catalog_sizes (product_id, size_name, sisplan_sku, sort_order) VALUES (12, '1', '00467-00007-1', 0) ON CONFLICT (product_id, size_name) DO NOTHING;
INSERT INTO order_catalog_sizes (product_id, size_name, sisplan_sku, sort_order) VALUES (12, '2', '00467-9-2', 1) ON CONFLICT (product_id, size_name) DO NOTHING;
INSERT INTO order_catalog_sizes (product_id, size_name, sisplan_sku, sort_order) VALUES (12, '3', '00467-9-3', 2) ON CONFLICT (product_id, size_name) DO NOTHING;
INSERT INTO order_catalog_sizes (product_id, size_name, sisplan_sku, sort_order) VALUES (12, '4', '00467-00001-4', 3) ON CONFLICT (product_id, size_name) DO NOTHING;
INSERT INTO order_catalog_sizes (product_id, size_name, sisplan_sku, sort_order) VALUES (12, '6', '00467-00007-6', 4) ON CONFLICT (product_id, size_name) DO NOTHING;
INSERT INTO order_catalog_sizes (product_id, size_name, sisplan_sku, sort_order) VALUES (12, '8', '00467-00001-8', 5) ON CONFLICT (product_id, size_name) DO NOTHING;
INSERT INTO order_catalog_sizes (product_id, size_name, sisplan_sku, sort_order) VALUES (12, '10', '00467-9-10', 6) ON CONFLICT (product_id, size_name) DO NOTHING;
INSERT INTO order_catalog_sizes (product_id, size_name, sisplan_sku, sort_order) VALUES (13, '1', '00250-00039-1', 0) ON CONFLICT (product_id, size_name) DO NOTHING;
INSERT INTO order_catalog_sizes (product_id, size_name, sisplan_sku, sort_order) VALUES (13, '2', '00250-00123-2', 1) ON CONFLICT (product_id, size_name) DO NOTHING;
INSERT INTO order_catalog_sizes (product_id, size_name, sisplan_sku, sort_order) VALUES (13, '3', '00250-00040-3', 2) ON CONFLICT (product_id, size_name) DO NOTHING;
INSERT INTO order_catalog_sizes (product_id, size_name, sisplan_sku, sort_order) VALUES (13, '4', '00250-00096-4', 3) ON CONFLICT (product_id, size_name) DO NOTHING;
INSERT INTO order_catalog_sizes (product_id, size_name, sisplan_sku, sort_order) VALUES (13, '6', '00250-00083-6', 4) ON CONFLICT (product_id, size_name) DO NOTHING;
INSERT INTO order_catalog_sizes (product_id, size_name, sisplan_sku, sort_order) VALUES (13, '8', '00250-00057-8', 5) ON CONFLICT (product_id, size_name) DO NOTHING;
INSERT INTO order_catalog_sizes (product_id, size_name, sisplan_sku, sort_order) VALUES (13, '10', '00250-00051-10', 6) ON CONFLICT (product_id, size_name) DO NOTHING;
INSERT INTO order_catalog_sizes (product_id, size_name, sisplan_sku, sort_order) VALUES (14, '1', '00416-00069-1', 0) ON CONFLICT (product_id, size_name) DO NOTHING;
INSERT INTO order_catalog_sizes (product_id, size_name, sisplan_sku, sort_order) VALUES (14, '2', '00416-00103-2', 1) ON CONFLICT (product_id, size_name) DO NOTHING;
INSERT INTO order_catalog_sizes (product_id, size_name, sisplan_sku, sort_order) VALUES (14, '3', '00416-00079-3', 2) ON CONFLICT (product_id, size_name) DO NOTHING;
INSERT INTO order_catalog_sizes (product_id, size_name, sisplan_sku, sort_order) VALUES (14, '4', '00416-00001-4', 3) ON CONFLICT (product_id, size_name) DO NOTHING;
INSERT INTO order_catalog_sizes (product_id, size_name, sisplan_sku, sort_order) VALUES (14, '6', '00416-00043-6', 4) ON CONFLICT (product_id, size_name) DO NOTHING;
INSERT INTO order_catalog_sizes (product_id, size_name, sisplan_sku, sort_order) VALUES (14, '8', '00416-00072-8', 5) ON CONFLICT (product_id, size_name) DO NOTHING;
INSERT INTO order_catalog_sizes (product_id, size_name, sisplan_sku, sort_order) VALUES (14, '10', '00416-00041-10', 6) ON CONFLICT (product_id, size_name) DO NOTHING;
INSERT INTO order_catalog_sizes (product_id, size_name, sisplan_sku, sort_order) VALUES (15, '1', '00400-00074-1', 0) ON CONFLICT (product_id, size_name) DO NOTHING;
INSERT INTO order_catalog_sizes (product_id, size_name, sisplan_sku, sort_order) VALUES (15, '2', '00400-00140-2', 1) ON CONFLICT (product_id, size_name) DO NOTHING;
INSERT INTO order_catalog_sizes (product_id, size_name, sisplan_sku, sort_order) VALUES (15, '3', '00400-00009-3', 2) ON CONFLICT (product_id, size_name) DO NOTHING;
INSERT INTO order_catalog_sizes (product_id, size_name, sisplan_sku, sort_order) VALUES (15, '4', '00400-00080-4', 3) ON CONFLICT (product_id, size_name) DO NOTHING;
INSERT INTO order_catalog_sizes (product_id, size_name, sisplan_sku, sort_order) VALUES (15, '6', '00400-00142-6', 4) ON CONFLICT (product_id, size_name) DO NOTHING;
INSERT INTO order_catalog_sizes (product_id, size_name, sisplan_sku, sort_order) VALUES (15, '8', '00400-00102-8', 5) ON CONFLICT (product_id, size_name) DO NOTHING;
INSERT INTO order_catalog_sizes (product_id, size_name, sisplan_sku, sort_order) VALUES (15, '10', '00400-00040-10', 6) ON CONFLICT (product_id, size_name) DO NOTHING;
INSERT INTO order_catalog_sizes (product_id, size_name, sisplan_sku, sort_order) VALUES (16, 'RN', '00565-00077-RN', 0) ON CONFLICT (product_id, size_name) DO NOTHING;
INSERT INTO order_catalog_sizes (product_id, size_name, sisplan_sku, sort_order) VALUES (16, 'P', '00565-00096-P', 1) ON CONFLICT (product_id, size_name) DO NOTHING;
INSERT INTO order_catalog_sizes (product_id, size_name, sisplan_sku, sort_order) VALUES (16, 'M', '00565-00115-M', 2) ON CONFLICT (product_id, size_name) DO NOTHING;
INSERT INTO order_catalog_sizes (product_id, size_name, sisplan_sku, sort_order) VALUES (16, 'G', '00565-00009-G', 3) ON CONFLICT (product_id, size_name) DO NOTHING;
INSERT INTO order_catalog_sizes (product_id, size_name, sisplan_sku, sort_order) VALUES (16, 'GG', '00565-00083-GG', 4) ON CONFLICT (product_id, size_name) DO NOTHING;
INSERT INTO order_catalog_sizes (product_id, size_name, sisplan_sku, sort_order) VALUES (17, 'P', '701-9-P', 0) ON CONFLICT (product_id, size_name) DO NOTHING;
INSERT INTO order_catalog_sizes (product_id, size_name, sisplan_sku, sort_order) VALUES (17, 'M', '701-00046-M', 1) ON CONFLICT (product_id, size_name) DO NOTHING;
INSERT INTO order_catalog_sizes (product_id, size_name, sisplan_sku, sort_order) VALUES (17, 'G', '701-00022-G', 2) ON CONFLICT (product_id, size_name) DO NOTHING;
INSERT INTO order_catalog_sizes (product_id, size_name, sisplan_sku, sort_order) VALUES (18, '10', '509-00041-10', 0) ON CONFLICT (product_id, size_name) DO NOTHING;
INSERT INTO order_catalog_sizes (product_id, size_name, sisplan_sku, sort_order) VALUES (18, '12', '509-00027-12', 1) ON CONFLICT (product_id, size_name) DO NOTHING;
INSERT INTO order_catalog_sizes (product_id, size_name, sisplan_sku, sort_order) VALUES (18, '14', '509-00028-14', 2) ON CONFLICT (product_id, size_name) DO NOTHING;
INSERT INTO order_catalog_sizes (product_id, size_name, sisplan_sku, sort_order) VALUES (19, '1', '00274-00039-1', 0) ON CONFLICT (product_id, size_name) DO NOTHING;
INSERT INTO order_catalog_sizes (product_id, size_name, sisplan_sku, sort_order) VALUES (19, '2', '00274-00003-2', 1) ON CONFLICT (product_id, size_name) DO NOTHING;
INSERT INTO order_catalog_sizes (product_id, size_name, sisplan_sku, sort_order) VALUES (19, '3', '00274-9-3', 2) ON CONFLICT (product_id, size_name) DO NOTHING;
INSERT INTO order_catalog_sizes (product_id, size_name, sisplan_sku, sort_order) VALUES (20, '1', '00612-00007-1', 0) ON CONFLICT (product_id, size_name) DO NOTHING;
INSERT INTO order_catalog_sizes (product_id, size_name, sisplan_sku, sort_order) VALUES (20, '2', '00612-9-2', 1) ON CONFLICT (product_id, size_name) DO NOTHING;
INSERT INTO order_catalog_sizes (product_id, size_name, sisplan_sku, sort_order) VALUES (20, '3', '00612-00043-3', 2) ON CONFLICT (product_id, size_name) DO NOTHING;
INSERT INTO order_catalog_sizes (product_id, size_name, sisplan_sku, sort_order) VALUES (20, '4', '00612-00075-4', 3) ON CONFLICT (product_id, size_name) DO NOTHING;
INSERT INTO order_catalog_sizes (product_id, size_name, sisplan_sku, sort_order) VALUES (20, '6', '00612-00007-6', 4) ON CONFLICT (product_id, size_name) DO NOTHING;
INSERT INTO order_catalog_sizes (product_id, size_name, sisplan_sku, sort_order) VALUES (20, '8', '00612-00043-8', 5) ON CONFLICT (product_id, size_name) DO NOTHING;
INSERT INTO order_catalog_sizes (product_id, size_name, sisplan_sku, sort_order) VALUES (20, '10', '00612-00007-10', 6) ON CONFLICT (product_id, size_name) DO NOTHING;
INSERT INTO order_catalog_sizes (product_id, size_name, sisplan_sku, sort_order) VALUES (21, '1', '317-00027-1', 0) ON CONFLICT (product_id, size_name) DO NOTHING;
INSERT INTO order_catalog_sizes (product_id, size_name, sisplan_sku, sort_order) VALUES (21, '2', '317-00027-2', 1) ON CONFLICT (product_id, size_name) DO NOTHING;
INSERT INTO order_catalog_sizes (product_id, size_name, sisplan_sku, sort_order) VALUES (21, '3', '317-9-3', 2) ON CONFLICT (product_id, size_name) DO NOTHING;
INSERT INTO order_catalog_sizes (product_id, size_name, sisplan_sku, sort_order) VALUES (22, 'RN', '00161-9-RN', 0) ON CONFLICT (product_id, size_name) DO NOTHING;
INSERT INTO order_catalog_sizes (product_id, size_name, sisplan_sku, sort_order) VALUES (22, 'P', '00161-9-P', 1) ON CONFLICT (product_id, size_name) DO NOTHING;
INSERT INTO order_catalog_sizes (product_id, size_name, sisplan_sku, sort_order) VALUES (22, 'M', '00161-00083-M', 2) ON CONFLICT (product_id, size_name) DO NOTHING;
INSERT INTO order_catalog_sizes (product_id, size_name, sisplan_sku, sort_order) VALUES (22, 'G', '00161-00043-G', 3) ON CONFLICT (product_id, size_name) DO NOTHING;
INSERT INTO order_catalog_sizes (product_id, size_name, sisplan_sku, sort_order) VALUES (22, 'GG', '00161-00043-GG', 4) ON CONFLICT (product_id, size_name) DO NOTHING;
INSERT INTO order_catalog_sizes (product_id, size_name, sisplan_sku, sort_order) VALUES (23, 'RN', '00127-00074-RN', 0) ON CONFLICT (product_id, size_name) DO NOTHING;
INSERT INTO order_catalog_sizes (product_id, size_name, sisplan_sku, sort_order) VALUES (23, 'P', '00127-00074-P', 1) ON CONFLICT (product_id, size_name) DO NOTHING;
INSERT INTO order_catalog_sizes (product_id, size_name, sisplan_sku, sort_order) VALUES (23, 'M', '00127-00009-M', 2) ON CONFLICT (product_id, size_name) DO NOTHING;
INSERT INTO order_catalog_sizes (product_id, size_name, sisplan_sku, sort_order) VALUES (23, 'G', '00127-9-G', 3) ON CONFLICT (product_id, size_name) DO NOTHING;
INSERT INTO order_catalog_sizes (product_id, size_name, sisplan_sku, sort_order) VALUES (23, 'GG', '00127-9-GG', 4) ON CONFLICT (product_id, size_name) DO NOTHING;
INSERT INTO order_catalog_sizes (product_id, size_name, sisplan_sku, sort_order) VALUES (24, 'RN', '00133-00003-RN', 0) ON CONFLICT (product_id, size_name) DO NOTHING;
INSERT INTO order_catalog_sizes (product_id, size_name, sisplan_sku, sort_order) VALUES (24, 'P', '00133-00003-P', 1) ON CONFLICT (product_id, size_name) DO NOTHING;
INSERT INTO order_catalog_sizes (product_id, size_name, sisplan_sku, sort_order) VALUES (24, 'M', '00133-00003-M', 2) ON CONFLICT (product_id, size_name) DO NOTHING;
INSERT INTO order_catalog_sizes (product_id, size_name, sisplan_sku, sort_order) VALUES (24, 'G', '00133-00058-G', 3) ON CONFLICT (product_id, size_name) DO NOTHING;
INSERT INTO order_catalog_sizes (product_id, size_name, sisplan_sku, sort_order) VALUES (24, 'GG', '00133-00041-GG', 4) ON CONFLICT (product_id, size_name) DO NOTHING;
